### ISSUE TITLE
Dockerimage not available

### ISSUE THREAD

**Issue by dorianim** [immich-app/CLI#16]
Hi Alex,

When trying to pull the dockerimage, I get the following error:
![image](https://user-images.githubusercontent.com/30153207/186908001-200b66fa-e50a-43c0-b3c9-271558b34153.png)

Also, when clicking "packages" in the repo, GitHub says, there are no packages:
![image](https://user-images.githubusercontent.com/30153207/186908130-f3d356ca-4c4d-45b8-a39c-88665164fefa.png)

The counter on the repo page is still one, however:
![image](https://user-images.githubusercontent.com/30153207/186908200-bb52e2a5-0c97-40ff-91cf-e5c6a6d8b43a.png)

Maybe you left the package on private accidentally?

**Comment by alextran1502** [comment]
Fixed, the permission was changed after moving the repo to the organization
