### ISSUE TITLE
Not working on latest docker image

### ISSUE THREAD

**Issue by Nonobis** [immich-app/CLI#3]
Hello,

Trying to upload my exisint gimage.

Login OK but upload not working ...

I am running tools on window.

PS C:\Users\arnua> immich upload --email sss@gmail.com --password ssss --server 192.168.1.18 --port 3000 -d D:\Photos
[1] Pinging server...
Server status: OK
[2] Logging in...
Login status: OK
You are logged in as nonobis@gmail.com
[3] Checking directory...
Directory status: OK
[4] Indexing files...
Indexing file: OK
Found 209 assets in specified directory
[5] Gathering device's asset info from server...
A total of 209 assets will be uploaded to the server
Do you want to start upload now? (y/n) y
Start uploading...
 ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ 0% | ETA: 0s | 0/209
Error uploading asset Error: Request failed with status code 400

**Error uploading asset Error: No duration found!**

Error uploading asset Error: No duration found!

Error uploading asset Error: Request failed with status code 400

**Error uploading asset Error: Request failed with status code 400**

**Comment by alextran1502** [comment]
Hi,

This tool is currently out of date with the latest server. I will
Keep you updated when I have a chance to update this.

**Comment by sh000gun** [comment]
Hi @Nonobis.

As I knew this error was happened with ffmpeg installed on machine that ran script intermittently. I updated it with mediainfo and personally using it to upload around 15,000 assets to my immich server. You can take it https://github.com/sh000gun/immich_cli and test it with npm install in advanced. Please report if it works for you so I can create a PR to Alex

**Comment by Nonobis** [comment]
will try it tonight :)

**Comment by Nonobis** [comment]
sorry test your repo, error ffmpeg not found ..; i have tryed npm i ffmpeg-static in cli folder but same error ...

**Comment by sh000gun** [comment]
> 

Yes, we should have ffmpeg-static and itt seems that you don't have static ffmpeg installed on your machine. Please install it just like me cause the thumbnail generating needs it. For example with My M1
-
nguyen.doan@ITC-NGUYENDOAN-TSCDM0235 immich_cli % which ffmpeg
/usr/local/bin/ffmpeg
nguyen.doan@ITC-NGUYENDOAN-TSCDM0235 immich_cli % ffmpeg -version
ffmpeg version 5.0.1 Copyright (c) 2000-2022 the FFmpeg developers
built with Apple clang version 13.0.0 (clang-1300.0.29.30)
configuration: --prefix=/Volumes/tempdisk/sw --extra-cflags=-fno-stack-check --arch=arm64 --cc=/usr/bin/clang --enable-gpl --enable-libopenjpeg --enable-libopus --enable-libmp3lame --enable-libx264 --enable-libx265 --enable-libvpx --enable-libwebp --enable-libass --enable-libfreetype --enable-libtheora --enable-libvorbis --enable-libsnappy --enable-libaom --enable-libvidstab --enable-libzimg --enable-libsvtav1 --enable-version3 --pkg-config-flags=--static --disable-ffplay --enable-postproc --enable-nonfree --enable-neon --enable-runtime-cpudetect --disable-indev=qtkit --disable-indev=x11grab_xcb
libavutil      57. 17.100 / 57. 17.100
libavcodec     59. 18.100 / 59. 18.100
libavformat    59. 16.100 / 59. 16.100
libavdevice    59.  4.100 / 59.  4.100
libavfilter     8. 24.100 /  8. 24.100
libswscale      6.  4.100 /  6.  4.100
libswresample   4.  3.100 /  4.  3.100
libpostproc    56.  3.100 / 56.  3.100
--

Hope this helps!

**Comment by alextran1502** [comment]
CLI tool is now updated with version 0.4.0

**Comment by pluja** [comment]
Hi, I installed the latest version, and I am getting plenty of errors:

```
Error uploading asset [/home/user/STORAGE/DATA/oldgallery/images/2021/06-June/20210628-184744.mp4]: Error: Client network socket disconnected before secure TLS connection was established

Error uploading asset [/home/user/STORAGE/DATA/oldgallery/images/2021/09-September/20210911-201521.mp4]: Error: No duration found!
```

Although some images are being uploaded, but it is not shown. When I try to upload again, it does not try again with the failed files.

**Comment by alextran1502** [comment]
@pluja Can you help me check which CLI version are you on with 
```
immich --version
```

**Comment by alextran1502** [comment]
I've just fixed the progress bar issue - unrelated to the issue you are mentioning. Please make sure you are using `v0.8.0`

![image](https://user-images.githubusercontent.com/27055614/181828679-cf84b0b1-4c0b-4524-8014-c4d95b3855fc.png)

**Comment by alextran1502** [comment]
@pluja Please disregard the message above, I think I found the issue and I just pushed an update to npm. the newest version will be `0.9.0` I think it will fix the issue you are facing.

**Comment by pluja** [comment]
@alextran1502 I was using version 0.7.0 as it was what was being installed with `npm i`. Now I updated it and it shows latest version (`0.12.0`) and it is working as expected.

Uploaded 3000 items perfectly.

**Comment by pluja** [comment]
@alextran1502 I see one other issue. The uploaded files show a "NO EXIF INFO AVAILABLE" when trying to see the exif info in the web-ui. But I know most of the images have exif data, at least the device data info.

Is there any issue with the exif data? May it be that it is processed after the upload?
