### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by oddlama** [immich-app/CLI#30]
Hi! When I use this tool to upload a folder with a lot of videos (~2-4GB each), the node process will start hogging memory and be killed by the OOM killer after some time. I'm unfortunately not sure what is causing this, maybe you know more.

**Comment by alextran1502** [comment]
Can you try the option `--thread 1` to see if you still have the problem. It is the latest change we added to the tool

**Comment by oddlama** [comment]
Yup still growing quickly to 50GB, then it gets killed

**Comment by alextran1502** [comment]
@zackpollard Any thought on this? Perhaps the CLI read the file content to the memory before sending instead of using stream so such problem occurs?

**Comment by oddlama** [comment]
I might have some more insights. I've temporarily added a significant delay after each operation (30 seconds), which seems to be enough to allow the system to reclaim the now unused memory. Even with the default 5 threads loading big 4 Gig files, I shouldn't reach my memory limit. But when the app doesn't release the resources quickly enough, the new threads seem to allocate new memory quicker than the old one is released causing the gradual buildup. Maybe there is some way to tell node to aggressively release resources after each operation.

**Comment by zackpollard** [comment]
This is very odd, I have been doing a huge amount of uploads on my server with batches of up to 11k files in one go, consisting of some fairly large video files (albeit not all videos). It is quite possible the CLI is loading the file into memory before sending it which could cause this issue, although I wouldn't expect to see it when running with a single thread as node should clean up when memory pressure increases.

**Comment by oddlama** [comment]
I did the same, but all the videos came last, so I was left with 900 videos of varying size. Around 300 were above 2GB. With 5 threads, this finally exhausted 50GB of RAM on my system.

Unfortunately I can't share these personal files, but they are just generic mp4 files from a regular high-end Android phone. This most definitely feels like a memory pressure problem, especially since my sleep(30) addition fixed it. For some reason the memory is just cleaned very slowly (as if there were many small chunks that were collected individually by GC)
