### ISSUE TITLE
pictures not added to the album

### ISSUE THREAD

**Issue by spupuz** [immich-app/CLI#33]
while uploading several folder got errors because of gif files present in some of the folders.
Album was not completely populated, so re-run the immich cli without the gif it has uploaded the missing pictures but not updated the album with the one already uploaded.

Can a check be implemented in order that if a picture is already uploaded but not in a album will be put in the album?

additionally can you just skip not supported formats?

**Comment by assid2** [comment]
Also if you upload images and for some reason the upload is cut half way through, re-running the command only gets the remaining images into the album.
I've noticed that the albums are generated and linked at the end of the upload process ,  Hence only images during that  (new) session  are linked to the album.

**Comment by alextran1502** [comment]
Resolved in #45
