### ISSUE TITLE
It is recursive - Documentation Improvement

### ISSUE THREAD

**Issue by Pixelartist** [immich-app/CLI#36]
Hello there,

I just wasted 30 minutes on trying to figure out - how do i tell this thing to go in each of my google takeout folders and execute this command. I felt really close to a solution - where I accidently ran the command from the main folder - and voila - it is already recursing through the folders in the folder you start.
Please mention it somewhere in the documentation - and for peeps who do not like to have it suck up all images, maybe an option to not do it.

**Comment by alextran1502** [comment]
Fair, you can also go to each folder and execute the command from that folder if you don't want the nested directory to be scanned
