### ISSUE TITLE
Unable to upload images downloaded from the Signal texting app.

### ISSUE THREAD

**Issue by njakes** [immich-app/CLI#37]
I know this may seem kind of niche but I wanted to share my experience anyway.  I have the server up and running and everything is working fine.  I also have the app on my iPhone, which automatically uploads my images.  
I have been using the cli docker image to upload my large back log of images from previous years.  In doing so I noticed that all images that were downloaded using the signal app then transfered to the server wont upload.  They all say unknown file format in the error log.  The odd thing about this is, the iPhone app will upload them just fine. It shows the date they were taken and the the display properly as jpg images.  

I don't know what could be the cause of this right now but I thought I would share.  I am testing multiple picture management services at the same time so I also use PhotoSync on the iPhone to transfer them to my server as well as upload inside the Immich app.

**Comment by njakes** [comment]
What would be the best way to share it with you?

**Comment by alextran1502** [comment]
Ah no problem 😀
