### ISSUE TITLE
Error navigating to directory - check directory path

### ISSUE THREAD

**Issue by InsanePirate** [immich-app/CLI#39]
Hi,

I have Immich installed in Unraid via the Docker Compose Manager plugin and I'm now trying to use the CLI tools to import a few thousand photos inside 1 folder (I named it "files") and scattered among half a dozen subfolders (with different names).

I opened the console inside the Immich Server container (/usr/src/app) and installed from the NPM repository. I then updated to version 8.19.3 as suggested  and ran the upload command.

Pinging the server went OK, Logging in went OK, but when checking the directory, I got this error: 
Error navigating to directory - check directory path

I tried using multiple paths and copying the folder I wanted to upload to multiple locations, but I think I'm missing something here.

I first tried using unraid's folder path, of course that didnt't work. I then copied the "files" folder into the Upload Location folder and set the directory for upload as upload/files. Didn't work. Then I set the directory for upload as /usr/src/app/upload/files - didn't work. 
Tried a number of things, details of which I can't remeber by now, but at this point I'm out of ideas. Any tips?

Thanks.

**Comment by bo0tzz** [comment]
The cli isn't intended for using inside of the immich container. You should run it on the system where you have your photos saved. If it's easier, there is also a dockerized version of the cli you can use (check the readme.)

**Comment by mikimuster** [comment]
Hello. I am facing the same error but I am running the latest version from NPM and I can't figure out the correct way to specify my directory parameter: 

Example: sudo immich upload --key key123--server http://server:2283/api /mnt/images

Thanks
