### ISSUE TITLE
Unable to upload some files

### ISSUE THREAD

**Issue by joeShuff** [immich-app/CLI#42]
When trying to bulk upload some photos I'm getting some that won't go up. A mix of `.gif` `.webp`  `.jpg`. All with error

`[Error: Unknown file format]` 
Which seems odd because other images of that filetype uploaded fine.

The images themselves open fine on my PC.

If you need access to one of the files then I can provide them.

![image](https://user-images.githubusercontent.com/15524362/204899355-1885638c-2c33-40cd-99ac-bf0babd6751a.png)

**Comment by alextran1502** [comment]
Can you help provide one of the types?

**Comment by joeShuff** [comment]
This is one of the files that failed to upload.

Not sure if attaching to a github issue messes with the file format a bit so I've uploaded it to google drive as a public file and will delete soon after you've downloaded it. If you need access to more of the files I can privately send you a DL link on the discord.

https://drive.google.com/file/d/1UI0Spz-UXuNZadt4wEVyC1rxzmOB5d5Q/view?usp=share_link
