### ISSUE TITLE
[Bug] Multiple albums

### ISSUE THREAD

**Issue by veloxy** [immich-app/CLI#46]
I've exported my photos for Google Photos using Google Takeout, in Google Photos I had photos in multiple albums, something which Immich also supports. However, the CLI tool doesn't move the photos into all of the albums, it's currently only moving it into one (I think the last one it was seen in? Or the first?).

**Given folder structure:**
```
Takeout/
- Album 1/
- - Photo 1.jpg
- - Photo 2.jpg
- Album 2/
- - Photo 1.jpg
```
*Note: Photo 1.jpg in both Album 1 and Album 2 are identical*

**Using the following command to import:**
```
immich upload --email <email> --password <password> --server http://<server>/api -d Takeout/ --album
```

**The result is:**
```
Album 1
- Photo 2
Album 2
- Photo 1
```

**The expected result:**
```
Album 1
- Photo 1
- Photo 2
Album 2
- Photo 1
```

Side note: It would be great if it would put the photos in the correct album(s) without having to re-upload all of them.

**Comment by bo0tzz** [comment]
The desired behaviour to get the result you want is the same as described in #45, so I'm closing this as a duplicate of that. Thanks for the report!

**Comment by veloxy** [comment]
@bo0tzz not sure how I missed that, sorry!
