### ISSUE TITLE
CLI upload creates duplicates with differnent resolutions

### ISSUE THREAD

**Issue by 0bscur3** [immich-app/CLI#50]
Hello, 

I am trying to upload a directory with the immich CLI, but the CLI does not scan the directory correctly. 

My directory has 7 files, but the tool calculates that it has to upload 28 files instead. On the server, I see that it uploaded each file four times with different prefixes:

* s800{{filename}}
* s100{{filename}}
* default{{filename}}
* {{filename}}

Can somebody find the issue?

```
immich upload --email xxx --password xxx --server http://xxx:2283/api -al 'xxx' -d 'xxx'
[1] Pinging server...
Server status: OK
[2] Logging in...
Login status: OK
You are logged in as xxx
[3] Checking directory...
Directory status: OK
[4] Indexing files...
Indexing file: OK
Found 28 assets in specified directory
[5] Gathering device's asset info from server...
A total of 28 assets will be uploaded to the server
Do you want to start upload now? (y/n) y
Start uploading...
Upload Progress | ████████████████████████████████████████ | 100% || 28/28 || Current file [/data/photos/xxx]
Creating albums...
Failed to upload 0 files  []
```

**Comment by bo0tzz** [comment]
The cli doesn't change the images in any way. Is there perhaps a hidden subfolder with the duplicate files?

**Comment by alextran1502** [comment]
Can you double check the directory path in the CLI command? Also do you know of other images that get uploaded?

**Comment by 0bscur3** [comment]
Indeed the folder contained a hidden folder with thumbnails from my previous NAS. 

Thanks for the quick help and pointing to the obvious error!
