### ISSUE TITLE
How can I find API Key

### ISSUE THREAD

**Issue by Gur15** [immich-app/CLI#57]
Hi 

I am going to try bulk upload, i know previously it was email and password but now it uses api key, but iam not sure how to find it.
I tried going to admin user section but i dont see api key section.
here is the command i am using.
node bin/index.js upload --key (unknown)--server http://x.x.x.x:2283/api -d C:/Users/HOME/Videos/BULK/
<img width="311" alt="Screenshot_1" src="https://user-images.githubusercontent.com/122171619/213811719-fa0c5dea-0dd4-4107-955a-71907efe85ef.png">

**Comment by bo0tzz** [comment]
You can get the API key from the user settings panel. https://immich.app/docs/features/bulk-upload#obtain-the-api-key

**Comment by Gur15** [comment]
<img width="951" alt="Screenshot_2" src="https://user-images.githubusercontent.com/122171619/213812198-5c67e0ba-bfa5-458d-abbd-23198551d998.png">

**Comment by Gur15** [comment]
I don't see api section

**Comment by bo0tzz** [comment]
Your server version is out of date, please update to the latest release.

**Comment by Gur15** [comment]
thank you so much, works like a charm.
