### ISSUE TITLE
After upgrading server to 1.43.0 CLI does not work

### ISSUE THREAD

**Issue by joshiparth1000** [immich-app/CLI#60]
I am trying to do bulk upload using the CLI after upgrading to 1.43.0 but I am getting the error message "Error logging in - check api key". This was working in 1.42.65.0_dev. I have tried using a new key but even that does not help.

**Comment by alextran1502** [comment]
Confirmed

**Comment by alextran1502** [comment]
Fixed in V1.43.1 https://github.com/immich-app/immich/releases/tag/v1.43.1
