### ISSUE TITLE
Add option to compute machine learning stuff locally before upload

### ISSUE THREAD

**Issue by simone-viozzi** [immich-app/CLI#84]

**Comment by bo0tzz** [comment]
The CLI is just a tool for getting files into the Immich server, we're not intending to add any more processing to it.

**Comment by bo0tzz** [comment]
@simone-viozzi for the scenario you're describing, you could run an extra instance of immich-microservices and machine-learning on your PC.

**Comment by simone-viozzi** [comment]
Is this documented somewhere?

I created this issue on immich-cli, because it is the tool people are going to use to bulk upload their existing library into immich.

So we can construct a docker-compose with `cli`, `microservices` and `machine-learning`. Run it on a separate machine and separate network, across internet maybe. And have it process the images before uploading them into the server?

That sounds like a solution to this issue to me.

**Comment by bo0tzz** [comment]
This wouldn't be preprocessing, but rather adding your PC as another worker for your Immich instance to use. You would need to connect it to the same library folder, postgres, and redis. There's no documentation as the setup depends quite a bit on what your particular environment looks like.
